#!/usr/bin/env python

import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

import argparse
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from qaisim import get_episode_interaction
from qaisim.qrl.module import Module
from qaisim.qrl import DeepQLearning, ParametrizedQC

plt.rcParams["font.family"] = "STIXGeneral"
tf.random.set_seed(12)


def train_q_val(args: argparse.Namespace) -> Module:
    num_qubits = 8 if args.backend == "pure" else 5
    num_layers = args.num_layers
    lrs = args.lrs
    num_actions = 5 if args.backend == "pure" else 2
    num_episodes = args.num_episodes

    episode_interaction, env = get_episode_interaction(
        dataset_file="data/qtasks_train.csv", **vars(args)
    )

    processor_id = None if args.backend == "pure" else "weber"
    paramatrized_qc = ParametrizedQC(num_qubits, num_layers, processor_id=processor_id)
    dql_agent = DeepQLearning(paramatrized_qc, num_actions, lrs=lrs)

    dql_agent.train(
        env=env,
        generate_episode=episode_interaction,
        num_episodes=num_episodes,
        batch_size=args.batch_size,
        threshold_reward=100,
    )

    return dql_agent


def main(args: argparse.Namespace) -> None:
    print("\n========= Training Configuration =========")

    for key, value in vars(args).items():
        print(f"{key:>15}: {value}")

    print("==========================================\n")
    save_dir = f"./results/dq_learning/{args.backend}"
    os.makedirs(save_dir, exist_ok=True)

    dql_agent = train_q_val(args)
    if dql_agent.model is None:
        raise RuntimeError("Deep Q-Learning Agent Model not defined")

    episode_rewards = dql_agent.episode_reward_history
    smoothed_rewards = np.convolve(episode_rewards, np.ones(20) / 20, mode="valid")

    episode_length = dql_agent.episode_length
    episode_length = np.convolve(episode_length, np.ones(20) / 20, mode="valid")

    plt.plot(episode_rewards, alpha=0.3)
    plt.plot(
        range(len(smoothed_rewards)), smoothed_rewards, color="blue", linewidth=1.5
    )
    plt.xlabel("Episode")
    plt.ylabel("Reward")
    plt.title("Deep Q-Learning Training", fontweight="bold")
    plt.grid()
    plt.savefig(os.path.join(save_dir, "dql_training.pdf"))

    plt.clf()

    plt.plot(episode_length, color="blue")
    plt.xlabel("Episode")
    plt.ylabel("Length")
    plt.title("Episode Length - DeepQLearning", fontweight="bold")
    plt.grid()
    plt.savefig(os.path.join(save_dir, "episode_length.pdf"))

    dql_agent.model.save_weights(os.path.join(save_dir, "model.h5"))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(usage="%(prog)s [options]")

    parser.add_argument(
        "--backend",
        type=str,
        default="pure",
        choices=["pure", "noisy"],
        help="Type of backend - pure or noisy (weber noise)",
    )
    parser.add_argument(
        "--num_layers", type=int, default=5, help="Number of PQC layers"
    )
    parser.add_argument(
        "--num_episodes", type=int, default=1500, help="Number of training episodes"
    )
    parser.add_argument("--batch_size", type=int, default=10, help="Batch Size")
    parser.add_argument(
        "--lrs",
        type=tuple,
        default=(0.03, 0.01, 0.03),
        help="Learning rates for model",
    )

    args = parser.parse_args()
    main(args)
