#!/usr/bin/env python

import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

import argparse
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from qaisim.qrl.module import EpisodeCallable, EpisodicOutcome, Module
from qaisim.utils import Dataset
from qaisim.qrl import QRLEnv, PolicyGradient, ParametrizedQC
from qaisim.qrl.env_qnodes import ibm_qnodes, qnodes_for_noisy_exp

from collections import defaultdict
from typing import Any

plt.rcParams["font.family"] = "STIXGeneral"
tf.random.set_seed(12)


def get_episode_gen(args: argparse.Namespace) -> EpisodeCallable:
    num_actions = 5 if args.backend == "pure" else 2

    dataset = Dataset(file_name="./data/qtasks_train.csv")
    STATE_BOUNDS = [30] * num_actions + [60, 50, 200000]
    env_qnodes = ibm_qnodes if args.backend == "pure" else qnodes_for_noisy_exp

    def generate_episodes(
        model: tf.keras.Model, n_actions: int, n_episodes: int | float, s: Any = None
    ) -> EpisodicOutcome:
        if not isinstance(n_episodes, int):
            raise RuntimeError(
                f"Expected n_episodes to be of type int, recieved {type(n_episodes)}"
            )

        episodes: EpisodicOutcome = [defaultdict(list) for _ in range(n_episodes)]

        # load environments for each episode
        envs = [QRLEnv(dataset, env_qnodes) for _ in range(n_episodes)]
        done = [False for _ in range(n_episodes)]

        states = [e.reset() for e in envs]
        states = [_state[0] for _state in states]

        while not all(done):
            states = [
                np.concatenate(
                    [
                        state["qnode_queued_tasks"],
                        state["qtask_arrival_time"],
                        state["qtask_num_qubits"],
                        state["qtask_circuit_layers"],
                    ]
                )
                if state
                else np.array([])
                for state in states
            ]

            unfinished_ids = [i for i in range(n_episodes) if not done[i]]
            normalized_states = [
                s / STATE_BOUNDS for i, s in enumerate(states) if not done[i]
            ]

            for i, state in zip(unfinished_ids, normalized_states):
                episodes[i]["states"].append(state)

            states = tf.convert_to_tensor(normalized_states)
            action_probs = model([states])

            states = [None for _ in range(n_episodes)]
            for i, policy in zip(unfinished_ids, action_probs.numpy()):
                action = np.random.choice(n_actions, p=policy)
                states[i], reward, done[i], _, x = envs[i].step(action)
                episodes[i]["actions"].append(action)
                episodes[i]["rewards"].append(reward)
                episodes[i]["waiting_time"].append(x["waiting_time"])

        return episodes

    return generate_episodes


def train_policy(args: argparse.Namespace) -> Module:
    num_qubits = 8 if args.backend == "pure" else 5
    num_layers = args.num_layers
    lrs = (0.03, 0.05, 0.03)
    num_actions = 5 if args.backend == "pure" else 2
    num_episodes = args.num_episodes

    generate_episodes = get_episode_gen(args)

    paramatrized_qc = ParametrizedQC(num_qubits, num_layers)
    policy_gradient_agent = PolicyGradient(paramatrized_qc, num_actions, lrs=lrs)

    policy_gradient_agent.train(
        generate_episodes,
        num_episodes=num_episodes,
        batch_size=args.batch_size,
        threshold_reward=100,
    )

    return policy_gradient_agent


def main(args: argparse.Namespace) -> None:
    print("\n========= Training Configuration =========")

    for key, value in vars(args).items():
        print(f"{key:>15}: {value}")

    print("==========================================\n")

    save_dir = f"results/policy/{args.backend}"
    os.makedirs(save_dir, exist_ok=True)

    policy_grad_agent = train_policy(args)
    if policy_grad_agent.model is None:
        raise RuntimeError("Policy Gradient Agent Model not defined")

    episode_rewards = policy_grad_agent.episode_reward_history
    smoothed_rewards = np.convolve(episode_rewards, np.ones(20) / 20, mode="valid")

    episode_length = policy_grad_agent.episode_length
    episode_length = np.convolve(episode_length, np.ones(20) / 20, mode="valid")

    plt.plot(episode_rewards, alpha=0.3)
    plt.plot(
        range(len(smoothed_rewards)), smoothed_rewards, color="blue", linewidth=1.5
    )
    plt.xlabel("Episode")
    plt.ylabel("Reward")
    plt.title("Policy Gradient Training", fontweight="bold")
    plt.savefig(os.path.join(save_dir, "policy_training.pdf"))

    plt.clf()

    plt.plot(episode_length, color="blue")
    plt.xlabel("Episode")
    plt.ylabel("Length")
    plt.title("Episode Length - Policy", fontweight="bold")
    plt.savefig(os.path.join(save_dir, "episode_length.pdf"))

    policy_grad_agent.model.save_weights(os.path.join(save_dir, "model.h5"))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(usage="%(prog)s [options]")

    parser.add_argument(
        "--backend",
        type=str,
        default="pure",
        choices=["pure", "noisy"],
        help="Type of backend - pure or noisy (weber noise)",
    )
    parser.add_argument(
        "--num_layers", type=int, default=5, help="Number of PQC layers"
    )
    parser.add_argument(
        "--num_episodes", type=int, default=1500, help="Number of training episodes"
    )
    parser.add_argument("--batch_size", type=int, default=10, help="Batch Size")
    parser.add_argument(
        "--lrs",
        type=(tuple),
        default=(0.03, 0.05, 0.03),
        help="Learning rates for model",
    )

    args = parser.parse_args()
    main(args)
